/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luciekopecka;

import java.awt.Color;
import java.util.ArrayList;

public class Kviz extends javax.swing.JFrame {
    protected Dotaznik dotaznik;
    protected int currentOtazkaIndex = 0;
    protected Otazka currentOtazka;
    protected ArrayList<Odpoved> currentOdpovedi;
    protected int currentSkore = 0;
    
    protected ArrayList<javax.swing.JButton> odpovediButtons;
    protected javax.swing.JFrame MainMenu;
    
    /**
     * Creates new form Kviz
     */
    public Kviz() {
        initComponents();
    }
    
    public Kviz(Dotaznik dotaznik, javax.swing.JFrame MainMenu) {
        initComponents();
        this.dotaznik = dotaznik;
        this.MainMenu = MainMenu;
        
        this.odpovediButtons = new ArrayList<javax.swing.JButton>();
        this.odpovediButtons.add(odpoved1);
        this.odpovediButtons.add(odpoved2);
        this.odpovediButtons.add(odpoved3);
        this.odpovediButtons.add(odpoved4);
        this.odpovediButtons.add(odpoved5);
        this.odpovediButtons.add(odpoved6);
        
        //this.continueButton.setVisible(false);
        this.setCurrentOtazka();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Otazka = new javax.swing.JPanel();
        textOtazky = new javax.swing.JLabel();
        odpoved1 = new javax.swing.JButton();
        odpoved2 = new javax.swing.JButton();
        odpoved3 = new javax.swing.JButton();
        odpoved4 = new javax.swing.JButton();
        odpoved5 = new javax.swing.JButton();
        odpoved6 = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();
        hodnota = new javax.swing.JLabel();
        skore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textOtazky.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textOtazky.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textOtazky.setText("HAHAHAHHA");

        odpoved1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved1.setFocusable(false);
        odpoved1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved1ActionPerformed(evt);
            }
        });

        odpoved2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved2.setFocusable(false);
        odpoved2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved2ActionPerformed(evt);
            }
        });

        odpoved3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved3.setFocusable(false);
        odpoved3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved3ActionPerformed(evt);
            }
        });

        odpoved4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved4.setFocusable(false);
        odpoved4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved4ActionPerformed(evt);
            }
        });

        odpoved5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved5.setFocusable(false);
        odpoved5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved5ActionPerformed(evt);
            }
        });

        odpoved6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        odpoved6.setFocusable(false);
        odpoved6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpoved6ActionPerformed(evt);
            }
        });

        continueButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        continueButton.setText("Pokračovat");
        continueButton.setFocusable(false);
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        hodnota.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hodnota.setText("Hodnota:");

        skore.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        skore.setText("Skóre: 0");

        javax.swing.GroupLayout OtazkaLayout = new javax.swing.GroupLayout(Otazka);
        Otazka.setLayout(OtazkaLayout);
        OtazkaLayout.setHorizontalGroup(
            OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtazkaLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OtazkaLayout.createSequentialGroup()
                        .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(odpoved1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odpoved2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OtazkaLayout.createSequentialGroup()
                                .addComponent(odpoved4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(odpoved6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OtazkaLayout.createSequentialGroup()
                                .addComponent(odpoved3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(odpoved5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(textOtazky, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OtazkaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(OtazkaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(skore, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hodnota, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        OtazkaLayout.setVerticalGroup(
            OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OtazkaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hodnota, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(skore, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOtazky, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odpoved3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odpoved5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odpoved1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(OtazkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(odpoved2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odpoved4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odpoved6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(continueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Otazka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Otazka, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setCurrentOtazka() {
        this.currentOtazka = this.dotaznik.getOtazkaOnIndex(this.currentOtazkaIndex);
        this.textOtazky.setText(this.currentOtazka.getTextOtazky());
        this.hodnota.setText("Hodnota: " + this.currentOtazka.getHodnota());
        this.currentOdpovedi = this.currentOtazka.getOdpovedi();
        
        for(javax.swing.JButton button : this.odpovediButtons) {
            PomocneFunkce.setButtonVisibilty(button, false);
        }
        
        PomocneFunkce.setButtonVisibilty(continueButton, false);
        
        int i = 0;
        for(; i < this.currentOdpovedi.size(); i++) {
            PomocneFunkce.setButtonVisibilty(this.odpovediButtons.get(i), true);
            this.odpovediButtons.get(i).setText(this.currentOdpovedi.get(i).getTextOdpovedi());
            this.odpovediButtons.get(i).setForeground(Color.BLACK);
        }
    }
    
    private void decideAnswer(int chosenAnswer) {
        if(chosenAnswer >= this.currentOdpovedi.size())
            return;
        int spravneIndex = this.currentOtazka.getCorrectOdpovedIndex();
        if(chosenAnswer == spravneIndex) {
            this.currentSkore += this.currentOtazka.getHodnota();
            this.skore.setText("Skóre: " + this.currentSkore);
            this.odpovediButtons.get(chosenAnswer).setForeground(Color.GREEN);
        }
        else {
            this.odpovediButtons.get(chosenAnswer).setForeground(Color.RED);
            this.odpovediButtons.get(spravneIndex).setForeground(Color.GREEN);
        }
        PomocneFunkce.setButtonVisibilty(continueButton, true);
        this.continueButton.setText("Pokračovat");
    }
    
    private void odpoved1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved1ActionPerformed
        this.decideAnswer(0);
    }//GEN-LAST:event_odpoved1ActionPerformed

    private void odpoved2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved2ActionPerformed
        this.decideAnswer(1);
    }//GEN-LAST:event_odpoved2ActionPerformed

    private void odpoved3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved3ActionPerformed
        this.decideAnswer(2);
    }//GEN-LAST:event_odpoved3ActionPerformed

    private void odpoved5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved5ActionPerformed
        this.decideAnswer(4);
    }//GEN-LAST:event_odpoved5ActionPerformed

    private void odpoved6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved6ActionPerformed
        this.decideAnswer(5);
    }//GEN-LAST:event_odpoved6ActionPerformed

    private void odpoved4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpoved4ActionPerformed
        this.decideAnswer(3);
    }//GEN-LAST:event_odpoved4ActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if(this.currentOtazkaIndex < this.dotaznik.otazky.size() - 1)
            this.currentOtazkaIndex++;
        else {
            Vysledky vysledky = new Vysledky(this.currentSkore, this.MainMenu, this);
            vysledky.setVisible(true);
            this.setVisible(false);
        }
        this.setCurrentOtazka();
    }//GEN-LAST:event_continueButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kviz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kviz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Otazka;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel hodnota;
    private javax.swing.JButton odpoved1;
    private javax.swing.JButton odpoved2;
    private javax.swing.JButton odpoved3;
    private javax.swing.JButton odpoved4;
    private javax.swing.JButton odpoved5;
    private javax.swing.JButton odpoved6;
    private javax.swing.JLabel skore;
    private javax.swing.JLabel textOtazky;
    // End of variables declaration//GEN-END:variables
}
