package luciekopecka;

import java.util.Scanner;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.filePathError.setVisible(false);
        //this.getRootPane().setDefaultButton(this.filePathLoadButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Zadani = new javax.swing.JPanel();
        filePathLabel = new javax.swing.JLabel();
        filePathLoadButton = new javax.swing.JButton();
        filePathField = new javax.swing.JTextField();
        filePathError = new javax.swing.JLabel();

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filePathLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        filePathLabel.setText("Zadejte název souboru pro načtení");
        filePathLabel.setToolTipText("");

        filePathLoadButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        filePathLoadButton.setText("Načíst");
        filePathLoadButton.setFocusable(false);
        filePathLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathLoadButtonActionPerformed(evt);
            }
        });

        filePathField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        filePathField.setText("input.txt");
        filePathField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filePathFieldKeyTyped(evt);
            }
        });

        filePathError.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        filePathError.setForeground(new java.awt.Color(255, 0, 0));
        filePathError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        filePathError.setToolTipText("");

        javax.swing.GroupLayout ZadaniLayout = new javax.swing.GroupLayout(Zadani);
        Zadani.setLayout(ZadaniLayout);
        ZadaniLayout.setHorizontalGroup(
            ZadaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZadaniLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZadaniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ZadaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZadaniLayout.createSequentialGroup()
                        .addComponent(filePathLabel)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZadaniLayout.createSequentialGroup()
                        .addComponent(filePathLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZadaniLayout.createSequentialGroup()
                        .addComponent(filePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        ZadaniLayout.setVerticalGroup(
            ZadaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZadaniLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(filePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filePathField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(filePathLoadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Zadani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Zadani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filePathLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathLoadButtonActionPerformed
        Dotaznik dotaznik = new Dotaznik();
        switch(dotaznik.nactiSoubor(this.filePathField.getText())) {
            case 1:
                dotaznik.randomizeOtazky();
                this.setVisible(false);
                Kviz kviz = new Kviz(dotaznik, this);
                kviz.setVisible(true);
                break;
            case -1:
                this.filePathError.setText("Soubor není ve správném formátu.");
                this.filePathError.setVisible(true);
                break;
            case -2:
                this.filePathError.setText("Soubor neexistuje.");
                this.filePathError.setVisible(true);
                break;
        }
    }//GEN-LAST:event_filePathLoadButtonActionPerformed

    private void filePathFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filePathFieldKeyTyped
        this.filePathError.setVisible(false);
    }//GEN-LAST:event_filePathFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Zadani;
    private javax.swing.JLabel filePathError;
    private javax.swing.JTextField filePathField;
    private javax.swing.JLabel filePathLabel;
    private javax.swing.JButton filePathLoadButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
