/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luciekopecka;

public class Vysledky extends javax.swing.JFrame {

    protected javax.swing.JFrame MainMenu;
    protected javax.swing.JFrame Kviz;
    
    /**
     * Creates new form Vysledky
     */
    public Vysledky() {
        initComponents();
    }
    
    /**
     * Inicializuje okno s výsledky. V paramaetrech jsou minulá okna aby se nemusely při případném puštění znovu vytvořit.
     * @param vysledneSkore
     * @param MainMenu
     * @param Kviz 
     */
    public Vysledky(int vysledneSkore, javax.swing.JFrame MainMenu, javax.swing.JFrame Kviz) {
        initComponents();
        this.MainMenu = MainMenu;
        this.Kviz = Kviz;
        this.labelVysledneSkore.setText("Výsledek: " + vysledneSkore + " bodů");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vysledky = new javax.swing.JPanel();
        labelVysledneSkore = new javax.swing.JLabel();
        buttonNacistJiny = new javax.swing.JButton();
        buttonKonec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelVysledneSkore.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelVysledneSkore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonNacistJiny.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonNacistJiny.setText("Načíst jiný soubor");
        buttonNacistJiny.setFocusable(false);
        buttonNacistJiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNacistJinyActionPerformed(evt);
            }
        });

        buttonKonec.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonKonec.setText("Ukončit program");
        buttonKonec.setFocusable(false);
        buttonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKonecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VysledkyLayout = new javax.swing.GroupLayout(Vysledky);
        Vysledky.setLayout(VysledkyLayout);
        VysledkyLayout.setHorizontalGroup(
            VysledkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VysledkyLayout.createSequentialGroup()
                .addGroup(VysledkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VysledkyLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(labelVysledneSkore, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VysledkyLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(buttonKonec)
                        .addGap(41, 41, 41)
                        .addComponent(buttonNacistJiny)))
                .addGap(130, 130, 130))
        );
        VysledkyLayout.setVerticalGroup(
            VysledkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VysledkyLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(labelVysledneSkore, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addGroup(VysledkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNacistJiny, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKonec, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vysledky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Vysledky, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vypne celý program a zahodí okna.
     * @param evt 
     */
    private void buttonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKonecActionPerformed
        this.MainMenu.dispose();
        this.Kviz.dispose();
        this.dispose();
    }//GEN-LAST:event_buttonKonecActionPerformed

    /**
     * Vrátí program zpět na okno načítací soubor.
     * @param evt 
     */
    private void buttonNacistJinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNacistJinyActionPerformed
        // TODO add your handling code here:
        this.MainMenu.setVisible(true);
        this.Kviz.dispose();
        this.dispose();
    }//GEN-LAST:event_buttonNacistJinyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vysledky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vysledky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vysledky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vysledky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vysledky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Vysledky;
    private javax.swing.JButton buttonKonec;
    private javax.swing.JButton buttonNacistJiny;
    private javax.swing.JLabel labelVysledneSkore;
    // End of variables declaration//GEN-END:variables
}
